channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=22.0.4
- pip:
  - mlflow
  - fsspec==2022.11.0
  - google-api-python-client==1.12.11
  - google-cloud-storage==1.44.0
  - pandas==1.5.2
  - pillow==9.3.0
  - scipy==1.9.3
  - tensorflow==2.11.0
name: mlflow-env
