name: CI
on:
  push:
    branches:
      - test
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Run ID
        id: run_id
        run: echo "id=$(sed "4q;d" build_data.txt)" >> $GITHUB_OUTPUT

      - name: Run ID output
        run: echo ${{ steps.run_id.outputs.id }}

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        env:
          BUCKET: ${{ secrets.BUCKET_NAME }}
          LOCATION_ROOT: ${{ secrets.LOCATION_ROOT }}
          EXPERIMENT_ID: ${{ secrets.EXPERIMENT_ID }}
        run: gsutil -m cp -r "gs://$BUCKET/$LOCATION_ROOT/$EXPERIMENT_ID/${{ steps.run_id.outputs.id }}/artifacts/model/*" ./docker_resources/temp_artifacts/

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          ls ./docker_resources/temp_artifacts/

      - name: Test DockerFile script
        shell: bash
        run: |
          cd ./docker_resources/
          ls 
          chmod 755 ./regex.bash
          ./regex.bash
          echo $(cat DockerFile)

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'CI Pipeline auto'

      # - uses: repo-sync/pull-request@v2
      #   name: pull-request
      #   with:
      #     destination_branch: "main"
      #     pr_title: "Pulling ${{ github.ref }} into main"
      #     pr_body: "👑 *An automated PR*"
      #     pr_reviewer: "mdeleon"
      #     pr_draft: true
      #     github_token: ${{ secrets.TOKEN_REPOSITORY }}
      #test
