name: CI
on:
  push:
    branches:
      - test
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Run ID
        id: run_id
        run: echo "id=$(sed "4q;d" build_data.txt)" >> $GITHUB_OUTPUT

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Clean temp_artifacts directory
        shell: bash
        run: |
          rm -r ./docker_resources/temp_artifacts/*

      - name: Use gcloud CLI
        env:
          BUCKET: ${{ secrets.BUCKET_NAME }}
          LOCATION_ROOT: ${{ secrets.LOCATION_ROOT }}
          EXPERIMENT_ID: ${{ secrets.EXPERIMENT_ID }}
        run: gsutil -m cp -r "gs://$BUCKET/$LOCATION_ROOT/$EXPERIMENT_ID/${{ steps.run_id.outputs.id }}/artifacts/model/*" ./docker_resources/temp_artifacts/

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "./docker_resources/temp_artifacts/data/*.h5"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        run: |
          mv ./docker_resources/temp_artifacts/data/*.h5 ./docker_resources/temp_artifacts/data.h5

      - name: Test DockerFile script
        shell: bash
        run: |
          cd ./docker_resources/
          chmod 755 ./regex.bash
          ./regex.bash

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./docker_resources/
          default_author: github_actions
          message: 'CI Pipeline auto'

      - name: Pull Request
        uses: repo-sync/pull-request@v2.9
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          # pr_reviewer: "mdeleon"
          # pr_draft: true
          github_token: ${{ secrets.TOKEN_REPOSITORY }}
